name: cpdaily

on:
  schedule:
    - cron:  '1 * * * *'
  watch:
    types: [ started ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 'Working'
      env:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
      run: python submit.py


